/**
 * Copyright 2017 Google Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
'use strict';

module.exports = [
  // 'https://www.aasaanjobs.com/',
  // 'https://www.adjarabet.com/',
  // 'https://www.airbnb.com.mt/',
  // 'https://www.airbnbchina.cn/',
  // 'https://www.algolia.com/',
  // 'https://www.ali-clicks.com/',
  // 'https://www.alibaba.com/',
  // 'https://www.aliexpress.com/',
  // 'https://www.aliimg.com/',
  // 'https://www.alligator.io/',
  // 'https://www.ampbyexample.com/',
  // 'https://www.avantrip.com/',
  // 'https://www.babe.news/',
  // 'https://www.babista.de/',
  // 'https://www.bdlive.co.za/',
  // 'https://www.belezanaweb.com.br/',
  // 'https://www.bitsofco.de/',
  // 'https://www.bland.is/',
  // 'https://www.browsersync.io/',
  // 'https://www.businesslive.co.za/',
  // 'https://www.busportal.pe/',
  // 'https://www.buyiphones.xyz/',
  'https://www.chromestatus.com/',
  // 'https://www.cilory.com/',
  // 'https://www.coolfund.io/',
  // 'https://www.datememe.com/',
  // 'https://www.dhgate.com/',
  // 'https://www.divyahimachal.com/',
  // 'https://www.dogobooks.com/',
  // 'https://www.dogomovies.com/',
  // 'https://www.dogonews.com/',
  // 'https://www.dominosweddingregistry.com/',
  // 'https://www.donacasa.es/',
  // 'https://www.douban.com/',
  // 'https://www.durahshon.tj/',
  // 'https://www.ele.me/',
  // 'https://www.family.me/',
  // 'https://www.fandango.com/',
  // 'https://www.fanmojo.in/',
  // 'https://www.fashionunited.it/',
  // 'https://www.flat.io/',
  // 'https://www.flipkart.com/',
  // 'https://www.geoexpat.com/',
  // 'https://www.goibibo.com/',
  // 'https://www.gumtree.co.za/',
  // 'https://www.hdfcred.com/',
  // 'https://www.hopamchuan.com/',
  'https://www.housing.com/',
  // 'https://www.housinganywhere.com/',
  // 'https://www.hpbn.co/',
  // 'https://www.imququ.com/',
  // 'https://www.infernojs.org/',
  // 'https://www.insider.in/',
  // 'https://www.jumia.com.gh/',
  // 'https://www.justfashionnow.com/',
  // 'https://www.justride.in/',
  // 'https://www.kawaiibeautyjapan.com/',
  // 'https://www.kfc.co.uk/',
  // 'https://www.kiwi.com/',
  // 'https://www.konga.com/',
  // 'https://www.lengstorf.com/',
  // 'https://www.liveauctioneers.com/',
  // 'https://www.logomakr.com/',
  // 'https://www.magicbricks.com/',
  // 'https://www.makaan.com/',
  // 'https://www.makemytrip.com/',
  // 'https://www.masterypoints.com/',
  // 'https://www.mbitcasino.com/',
  // 'https://www.megawins.com/',
  // 'https://www.mynet.com/',
  // 'https://www.nicheminer.co/',
  // 'https://www.noon.com/',
  // 'https://www.norgesautomaten.com/',
  // 'https://www.novaskin.me/',
  'https://www.olacabs.com/',
  // 'https://www.olx.com.ec/',
  // 'https://www.oresundsbron.com/',
  // 'https://www.paleoleap.com/',
  // 'https://www.pariksha.co/',
  'https://www.pureformulas.com/',
  // 'https://www.readme.me/',
  // 'https://www.redbus.pe/',
  // 'https://www.redmart.com/',
  // 'https://www.romanoriginals.co.uk/',
  // 'https://www.schulranzen.com/',
  // 'https://www.shakr.com/',
  // 'https://www.skypicker.com/',
  // 'https://www.snapdeal.com/',
  // 'https://www.socialcops.com/',
  // 'https://www.storiaimoveis.com.br/',
  // 'https://www.storywars.net/',
  // 'https://www.stylewe.com/',
  // 'https://www.thenews.com.pk/',
  // 'https://www.timroes.de/',
  // 'https://www.truecaller.com/',
  // 'https://www.unacademy.com/',
  // 'https://www.via.com/',
  // 'https://www.vivanuncios.com.mx/',
  // 'https://www.webcomponents.org/',
  'https://www.wego.ae/',
  // 'https://www.winnetnews.com/',
  // 'https://www.wunderino.com/',
  // 'https://www.yummypets.com/',
  // 'https://www.zalora.vn/',
  // 'https://flipkart.com/',
  // 'https://snapdeal.com/',
  // 'https://aliexpress.com/',
  // 'https://m.geo.tv/',
  // 'https://weather.com/fr-FR/',
  // 'https://billingsgazette.leeaws.com/pwa',
  // 'https://www.nfl.com/now',
  // 'https://storelocator.walgreens.com/#/find',
  // 'https://cnet.com/tech-today',
  // 'https://flat.io/',
  // 'https://selio.com/',
  // 'https://paperplanes.world/',
  // 'https://ride.lyft.com/',
  // 'https://beta.mic.com/',
  // 'https://pwa-cnne.firebaseapp.com/',
  // 'https://www.terra.com.br/',
  // 'https://www.terra.com.mx/',
  // 'https://app.infobae.com/',
  // 'https://www.interjet.com/',
  // 'https://vivanuncios.com/',
  // 'https://tkm.news/',
  // 'https://www.ft.com/',
  // 'https://pwa.mynet.com/',
  // 'https://www.tui.com/insider/',
  // 'https://m.airberlin.com/en/pwa',
  // 'https://housing.com/',
  // 'https://makemytrip.com/hotels',
  // 'https://app.kompas.com/',
  // 'https://m.magicbricks.com/',
  // 'https://m.bukalapak.com/',
  // 'https://m.alibaba.com/',
  // 'https://app.jalantikus.com/',
  // 'https://www.5milesapp.com/',
  // 'https://pwa.voot.com/',
  'https://react-hn.appspot.com/',
  'https://jakearchibald.github.io/svgomg/',
  // 'https://guitar-tuner.appspot.com/',
  // 'https://www.chromestatus.com/features',
  // 'https://meatscope.camera/',
  // 'https://events.google.com/io2016/',
  'https://shop.polymer-project.org/',

  'https://nytimes.com',
  'https://flipkart.com',
  // 'http://www.espn.com/',
  'https://www.washingtonpost.com/pwa/',
];